/* BANCO DE DADOS 
Banco Cinema: Script de povoamento
 Igor Terriaga Santos
*/

-- Unidade-Cinema --

INSERT INTO TB_UNIDADE_CINEMA VALUES( 'Cinema Itabaiana','O único cinema em Itabaiana')
INSERT INTO TB_UNIDADE_CINEMA VALUES( 'Cinema Jardins','O único cinema fora do shopping no bairro Jardins em Aracaju')
INSERT INTO TB_UNIDADE_CINEMA VALUES( 'Cinema Centro','Um dos poucos cinemas no Centro de Aracaju')

-- ENDERECOS --
-- rua, numero, cidade, bairro, complemento, estado, cep
INSERT INTO TB_ENDERECO VALUES ('Rua Riachuelo',65, 'Estância', 'Botequim','Casa', 'SE', '49500000');
INSERT INTO TB_ENDERECO VALUES ('Rua Moreira', 15, 'Umbaúba', 'José Ferreira','Apartamento: A8', 'SE', '495000487');
INSERT INTO TB_ENDERECO VALUES ('Rua B',223, 'Aracaju', 'Atalaia','Casa', 'AL', '49500987');
INSERT INTO TB_ENDERECO VALUES ('Rua SE',80, 'Aracaju', 'Bugio','Casa', 'SE', '49500000');
INSERT INTO TB_ENDERECO VALUES ('Rua E',154, 'Aracaju', 'Farolândia','Condomínio', 'SE', '49500000');
INSERT INTO TB_ENDERECO VALUES ('Rua Fonsceca',310, 'Aracaju', 'Atalaia','Apartamento: E26', 'SE', '49500000');
INSERT INTO TB_ENDERECO VALUES ('Rua X',76, 'São Cristóvão', 'Floresta','Casa', 'SE', '49500000');
INSERT INTO TB_ENDERECO VALUES ('Rua Comercial',214, 'Aracaju', 'Centro','Apartamento: G10', 'SE', '49500000');
INSERT INTO TB_ENDERECO VALUES ('Rua J',154, 'Aracaju', 'América','', 'SE', '49500000');
INSERT INTO TB_ENDERECO VALUES ('Rua São João',310, 'Aracaju', 'Atalaia','Apartamento: B15', 'SE', '49500000');
INSERT INTO TB_ENDERECO VALUES ('Rua C',44, 'Aracaju', 'Inácio Barbosa','Apartamento', 'SE', '495000061');
INSERT INTO TB_ENDERECO VALUES ('Rua Euclides',125, 'Aracaju', 'Centro','Apartamento: A5', 'SE', '49500097');
INSERT INTO TB_ENDERECO VALUES ('Rua Peixoto',77, 'Contagem', 'Centro','', 'MG', '49500000');
INSERT INTO TB_ENDERECO	VALUES ('Rua Valério',86, 'Aracaju', 'Bugio','Casa', 'SE', '49500000');

    
-- PESSOA --

INSERT INTO TB_PESSOA VALUES ('32165498712', 'M', 'Antonio', 'Nunes', '07-06-1987', 1);   
INSERT INTO TB_PESSOA VALUES ('98765412365', 'M', 'Rafael', 'Prado', '15-10-1992', 2);
INSERT INTO TB_PESSOA VALUES ('00012457899', 'F', 'Laura', 'Melo', '30-12-1990', 3);
INSERT INTO TB_PESSOA VALUES ('12454789632', 'M', 'Pedro', 'Luciano', '11-03-1995', 4);
INSERT INTO TB_PESSOA VALUES ('04512457896', 'F', 'Priscila', 'Santana', '26-05-1991', 5);
INSERT INTO TB_PESSOA VALUES ('01245368792', 'M', 'Roger', 'Machado', '20-03-1997', 6);
INSERT INTO TB_PESSOA VALUES ('95314558761', 'F', 'Luana', 'Oliveira', '04-09-1994', 7);
INSERT INTO TB_PESSOA VALUES ('13682457240', 'F', 'Maria', 'Santana', '02-11-1996', 8);
INSERT INTO TB_PESSOA VALUES ('45789654126', 'M', 'Carlos', 'Eduardo', '19-12-1993', 9);
INSERT INTO TB_PESSOA VALUES ('00245783650', 'F', 'Sara', 'Morais', '27-08-1998', 10);
INSERT INTO TB_PESSOA VALUES ('45789621452', 'M', 'Jimmie', 'Johnson', '04-08-1996', 11);
INSERT INTO TB_PESSOA VALUES ('02345698726', 'M', 'Edson', 'Motta', '23-07-1990', 12);
INSERT INTO TB_PESSOA VALUES ('57695298532', 'M', 'Eduardo', 'Braga', '24-10-1986', 13);
INSERT INTO TB_PESSOA VALUES ('14526751236', 'M', 'Valentino', 'Rossi', '24-10-1985', 14);

-- CLIENTE --
INSERT INTO TB_CLIENTE VALUES (5,5);
INSERT INTO TB_CLIENTE VALUES (6,6);
INSERT INTO TB_CLIENTE VALUES (7,7);
INSERT INTO TB_CLIENTE VALUES (8,8);
INSERT INTO TB_CLIENTE VALUES (9,9);
INSERT INTO TB_CLIENTE VALUES (10,10);
INSERT INTO TB_CLIENTE VALUES (11,11);
INSERT INTO TB_CLIENTE VALUES (12,12);
INSERT INTO TB_CLIENTE VALUES (13,13);
INSERT INTO TB_CLIENTE VALUES (14,14);

-- FUNCIONARIO --

INSERT INTO TB_FUNCIONARIO VALUES ('Gerente', 8, 1100.00, 5, 5);
INSERT INTO TB_FUNCIONARIO VALUES ('Bilheiteiro', 12, 650.00, 2, 2);
INSERT INTO TB_FUNCIONARIO VALUES ('Balconista da lanchonete', 12, 650.00, 3, 3);
INSERT INTO TB_FUNCIONARIO VALUES ('Operador de filme', 12, 750.00, 4, 4);


-- PRODUTO --
INSERT INTO TB_PRODUTO VALUES ('Pipoca', 5.00, 'SIM');
INSERT INTO TB_PRODUTO VALUES ('Biscoito', 5.00, 'SIM');
INSERT INTO TB_PRODUTO VALUES ('Chiclete', 2.00, 'SIM');
INSERT INTO TB_PRODUTO VALUES ('Coca Cola', 7.00, 'SIM');
INSERT INTO TB_PRODUTO VALUES ('Guaraná Antártica', 6.00, 'SIM');
INSERT INTO TB_PRODUTO VALUES ('Cachorro Quente', 5.00, 'SIM');
INSERT INTO TB_PRODUTO VALUES ('Água', 3.00, 'SIM');
INSERT INTO TB_PRODUTO VALUES ('Chocolate', 4.00, 'SIM');
INSERT INTO TB_PRODUTO VALUES ('Barra de Cereal', 3.00, 'SIM');

-- PRECO --
INSERT INTO TB_PRECO VALUES (10.00, 8.00, 30.00, 15.00);
INSERT INTO TB_PRECO VALUES (10.00, 6.00, 24.00, 12.00);
INSERT INTO TB_PRECO VALUES (6.00, 5.00, 15.00, 7.50);
INSERT INTO TB_PRECO VALUES (8.00, 6.00, 20.00, 10.00);
INSERT INTO TB_PRECO VALUES (7.00, 6.00, 16.00, 8.00);
INSERT INTO TB_PRECO VALUES (9.00, 5.00, 25.00, 12.50);

-- SALA --
INSERT INTO TB_SALA VALUES (1);
INSERT INTO TB_SALA VALUES (2);
INSERT INTO TB_SALA VALUES (3);
INSERT INTO TB_SALA VALUES (4);
INSERT INTO TB_SALA VALUES (5);
    
-- POLTRONA --
-- SALA 1 --
INSERT INTO TB_POLTRONA VALUES (1, 1, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (2, 1, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (3, 1, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (4, 1, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (5, 1, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (6, 1, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (7, 1, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (8, 1, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (9, 1, 'C', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (10, 1, 'C', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (11, 1, 'C', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (12, 1, 'C', 'ATIVA');    
INSERT INTO TB_POLTRONA VALUES (13, 1, 'D', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (14, 1, 'D', 'ATIVA');  
INSERT INTO TB_POLTRONA VALUES (15, 1, 'D', 'ATIVA');  
INSERT INTO TB_POLTRONA VALUES (16, 1, 'D', 'ATIVA'); 

-- SALA 2 --
INSERT INTO TB_POLTRONA VALUES (1, 2, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (2, 2, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (3, 2, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (4, 2, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (5, 2, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (6, 2, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (7, 2, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (8, 2, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (9, 2, 'C', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (10, 2, 'C', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (11, 2, 'C', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (12, 2, 'C', 'ATIVA');    
INSERT INTO TB_POLTRONA VALUES (13, 2, 'D', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (14, 2, 'D', 'DESATIVADA');  
INSERT INTO TB_POLTRONA VALUES (15, 2, 'D', 'ATIVA');  
INSERT INTO TB_POLTRONA VALUES (16, 2, 'D', 'DESATIVADA');  
    
-- SALA 3 --
INSERT INTO TB_POLTRONA VALUES (1, 3, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (2, 3, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (3, 3, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (4, 3, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (5, 3, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (6, 3, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (7, 3, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (8, 3, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (9, 3, 'C', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (10, 3, 'C', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (11, 3, 'C', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (12, 3, 'C', 'ATIVA');    
INSERT INTO TB_POLTRONA VALUES (13, 3, 'D', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (14, 3, 'D', 'DESATIVADA');  
INSERT INTO TB_POLTRONA VALUES (15, 3, 'D', 'DESATIVADA');  
INSERT INTO TB_POLTRONA VALUES (16, 3, 'D', 'DESATIVADA');  
    
-- SALA 4 --
INSERT INTO TB_POLTRONA VALUES (1, 4, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (2, 4, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (3, 4, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (4, 4, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (5, 4, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (6, 4, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (7, 4, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (8, 4, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (9, 4, 'C', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (10, 4, 'C', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (11, 4, 'C', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (12, 4, 'C', 'ATIVA');    
INSERT INTO TB_POLTRONA VALUES (13, 4, 'D', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (14, 4, 'D', 'ATIVA');  
INSERT INTO TB_POLTRONA VALUES (15, 4, 'D', 'ATIVA');  
INSERT INTO TB_POLTRONA VALUES (16, 4, 'D', 'DESATIVADA');  
    
-- SALA 5 --
INSERT INTO TB_POLTRONA  VALUES (1, 5, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (2, 5, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (3, 5, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (4, 5, 'A', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (5, 5, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (6, 5, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (7, 5, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (8, 5, 'B', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (9, 5, 'C', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (10, 5, 'C', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (11, 5, 'C', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (12, 5, 'C', 'DESATIVADA');    
INSERT INTO TB_POLTRONA VALUES (13, 5, 'D', 'ATIVA');
INSERT INTO TB_POLTRONA VALUES (14, 5, 'D', 'DESATIVADA');  
INSERT INTO TB_POLTRONA VALUES (15, 5, 'D', 'ATIVA');  
INSERT INTO TB_POLTRONA VALUES (16, 5, 'D', 'ATIVA');  
    
-- FILME --
INSERT INTO TB_FILME VALUES ('Ruben Fleischer' , 16, 'Ficção científica', 'Venom','Eddie Brock é um 
    jornalista que investiga o misterioso trabalho de um cientista, suspeito de utilizar cobaias 
    humanas em experimentos mortais. Quando ele acaba entrando em contato com um simbionte alienígena.', 'Sony Pictures', 110);
    
INSERT INTO TB_FILME VALUES ('J. A. Bayona' , 14, 'Aventura', 'Jurassic World: Reino Ameaçado','Owen e Claire retornam à ilha Nublar para 
    salvar os dinossauros restantes de um vulcão que está prestes a entrar em erupção. Eles encontram novas e aterrorizantes 
    raças de dinossauros gigantes ao descobrir uma conspiração que ameaça todo o planeta.', 'Universal Pictures', 130);
    
INSERT INTO TB_FILME VALUES ('Jon Turteltaub' , 14, 'Ficção científica', 'Megatubarão','Na fossa mais profunda do Oceano Pacífico, 
    a tripulação de um submarino fica presa dentro do local após ser atacada por uma criatura pré-histórica que se achava estar extinta, 
    um tubarão de mais de 20 metros de comprimento, o Megalodon.', 'Warner Bros. Entertainment', 112);
    
INSERT INTO TB_FILME VALUES ('Corin Hardy' , 18, 'Terror', 'A Freira','Presa em um convento na Romênia, uma freira comete suicídio. 
    Para investigar o caso, o Vaticano envia um padre assombrado e uma noviça prestes a se tornar freira. Arriscando suas vidas, 
    a fé e até suas almas, os dois descobrem um segredo profano.', 'Sony Pictures', 100);
    
INSERT INTO TB_FILME VALUES ('David Leitch' , 14, 'Ficção científica', 'Deadpool 2','O supersoldado Cable vem do futuro com a missão de assassinar 
    o jovem mutante Russel e o mercenário Deadpool precisa aprender o que é ser herói de verdade para salvá-lo.', 'Marvel', 120);
    
INSERT INTO TB_FILME VALUES ('Sylvain White' , 16, 'Terror', 'Slender Man','As amigas Wren, Hallie, Chloe e Katie levam uma vida entediante no colégio. 
    Quando ouvem falar em um monstro chamado Slender Man, elas decidem invocá-lo por meio de um vídeo na Internet.', 'Sony Pictures Entertainment', 91);
    
 -- SESSAO --   
INSERT INTO TB_SESSAO VALUES ('04-09-2018', '19:00:00', 'DUBLADO', 1, 1);
INSERT INTO TB_SESSAO VALUES ('05-09-2018', '19:30:00', 'LEGENDADO', 2, 2);
INSERT INTO TB_SESSAO VALUES ('05-09-2018', '19:30:00', 'DUBLADO', 3, 3);    
INSERT INTO TB_SESSAO VALUES ('06-09-2018', '21:00:00', 'LEGENDADO', 4, 4);
INSERT INTO TB_SESSAO VALUES ('06-09-2018', '21:30:00', 'DUBLADO', 5, 5);


-- INGRESSOS COMPRADOS --
-- COMPRA 1 --
INSERT INTO TB_INGRESSO VALUES ('COMPRADO', 1, 1, 1, 1);
INSERT INTO TB_INGRESSO VALUES ('COMPRADO', 1, 1, 2, 1);
-- COMPRA 2 --    
INSERT INTO TB_INGRESSO VALUES ('COMPRADO', 2, 2, 1, 2);
-- COMPRA 3 --    
INSERT INTO TB_INGRESSO VALUES ('COMPRADO', 2, 2, 4, 2);
-- COMPRA 4 --    
INSERT INTO TB_INGRESSO VALUES ('COMPRADO', 3, 3, 2, 3);
-- COMPRA 5 --    
INSERT INTO TB_INGRESSO VALUES ('COMPRADO', 3, 3, 5, 3);
-- COMPRA 6 --    
INSERT INTO TB_INGRESSO VALUES ('COMPRADO', 4, 4, 2, 4);
-- COMPRA 7 --    
INSERT INTO TB_INGRESSO VALUES ('COMPRADO', 4, 4, 6, 4);
INSERT INTO TB_INGRESSO VALUES ('COMPRADO', 4, 4, 7, 4);
-- COMPRA 8 --    
INSERT INTO TB_INGRESSO VALUES ('COMPRADO', 5, 5, 2, 5);
INSERT INTO TB_INGRESSO VALUES ('COMPRADO', 5, 5, 3, 5); 
    
    
-- INGRESSOS À VENDA: SESSAO 1 --
INSERT INTO TB_INGRESSO VALUES ('À VENDA', 1, 1, 3, 1);
INSERT INTO TB_INGRESSO VALUES ('À VENDA', 1, 1, 4, 1);
INSERT INTO TB_INGRESSO VALUES ('À VENDA', 1, 1, 5, 1);
 
-- INGRESSOS À VENDA: SESSAO 2 --
INSERT INTO TB_INGRESSO VALUES ('À VENDA', 2, 2, 2, 2);
INSERT INTO TB_INGRESSO VALUES ('À VENDA', 2, 2, 3, 2);
INSERT INTO TB_INGRESSO VALUES ('À VENDA', 2, 2, 4, 2);
INSERT INTO TB_INGRESSO VALUES ('À VENDA', 2, 2, 5, 2);

-- INGRESSOS À VENDA: SESSAO 3 --
INSERT INTO TB_INGRESSO VALUES ('À VENDA', 3, 3, 4, 3);
INSERT INTO TB_INGRESSO VALUES ('À VENDA', 3, 3, 6, 3);
    
-- INGRESSOS À VENDA: SESSAO 4 --    
INSERT INTO TB_INGRESSO VALUES ('À VENDA', 4, 4, 1, 4);
INSERT INTO TB_INGRESSO VALUES ('À VENDA', 4, 4, 3, 4);
    
-- INGRESSOS À VENDA: SESSAO 5 --
INSERT INTO TB_INGRESSO VALUES ('À VENDA', 5, 5, 1, 5);
INSERT INTO TB_INGRESSO VALUES ('À VENDA', 5, 5, 4, 5);
    
-- PLANO_PRECO --
-- VEDIDOS --
INSERT INTO TB_PLANO_PRECO VALUES (1,1);  
INSERT INTO TB_PLANO_PRECO VALUES (2,1); 
INSERT INTO TB_PLANO_PRECO VALUES (3,2);
INSERT INTO TB_PLANO_PRECO VALUES (4,3);
INSERT INTO TB_PLANO_PRECO VALUES (5,3); 
INSERT INTO TB_PLANO_PRECO VALUES (6,3); 
INSERT INTO TB_PLANO_PRECO VALUES (7,4);
INSERT INTO TB_PLANO_PRECO VALUES (8,4);
INSERT INTO TB_PLANO_PRECO VALUES (9,4);
INSERT INTO TB_PLANO_PRECO VALUES (10,5);
INSERT INTO TB_PLANO_PRECO VALUES (11,5);

-- DISPONIVEIS --
INSERT INTO TB_PRECO_INGRESSO VALUES (12,1);
INSERT INTO TB_PRECO_INGRESSO VALUES (13,1);
INSERT INTO TB_PRECO_INGRESSO VALUES (14,1);    
INSERT INTO TB_PRECO_INGRESSO VALUES (15,2);
INSERT INTO TB_PRECO_INGRESSO VALUES (16,2);
INSERT INTO TB_PRECO_INGRESSO VALUES (17,2);
INSERT INTO TB_PRECO_INGRESSO VALUES (18,3);
INSERT INTO TB_PRECO_INGRESSO VALUES (19,3);
INSERT INTO TB_PRECO_INGRESSO VALUES (20,4);
INSERT INTO TB_PRECO_INGRESSO VALUES (21,4);
INSERT INTO TB_PRECO_INGRESSO VALUES (22,5);
INSERT INTO TB_PRECO_INGRESSO VALUES (23,5);
INSERT INTO TB_PRECO_INGRESSO VALUES (24,5);

-- Plataforma
INSERT INTO TB_PLATAFORMA VALUES ('ONLINE');
INSERT INTO TB_PLATAFORMA VALUES ('PRESENCIAL');


-- COMPRA --
INSERT INTO TB_COMPRA VALUES ('10001', '04-09-2018', '19:10:00', 87.00, 'À PRAZO', 1, 1, 1);
INSERT INTO TB_COMPRA VALUES ('10002', '05-09-2018', '19:15:00', 35.00, 'À VISTA', 2, 2, 2);
INSERT INTO TB_COMPRA VALUES ('10003', '05-09-2018', '19:18:00', 29.00, 'À VISTA', 3, 1, 3);
INSERT INTO TB_COMPRA VALUES ('10004', '05-09-2018', '19:21:00', 20.00, 'À VISTA', 4, 2, 1);
INSERT INTO TB_COMPRA VALUES ('10005', '05-09-2018', '19:25:00', 15.00, 'À VISTA', 5, 1, 2);
INSERT INTO TB_COMPRA VALUES ('10006', '06-09-2018', '20:52:00', 31.00, 'À VISTA', 6, 2, 2);
INSERT INTO TB_COMPRA VALUES ('10007', '06-09-2018', '20:56:00', 55.00, 'À PRAZO', 7, 1, 1);
INSERT INTO TB_COMPRA VALUES ('10008', '06-09-2018', '21:15:00', 45.00, 'À PRAZO', 8, 2, 2);
    
  
-- COMPRA_INGRESSO --
INSERT INTO TB_COMPRA_INGRESSO VALUES (1, 1);
INSERT INTO TB_COMPRA_INGRESSO VALUES (1, 2);
INSERT INTO TB_COMPRA_INGRESSO VALUES (2, 3);
INSERT INTO TB_COMPRA_INGRESSO VALUES (3, 4);
INSERT INTO TB_COMPRA_INGRESSO VALUES (4, 5);
INSERT INTO TB_COMPRA_INGRESSO VALUES (5, 6);
INSERT INTO TB_COMPRA_INGRESSO VALUES (6, 7);
INSERT INTO TB_COMPRA_INGRESSO VALUES (7, 8);
INSERT INTO TB_COMPRA_INGRESSO VALUES (7, 9);
INSERT INTO TB_COMPRA_INGRESSO VALUES (8, 10);
INSERT INTO TB_COMPRA_INGRESSO VALUES (8, 11);
    
-- COMPRA_PRODUTO --    
INSERT INTO TB_COMPRA_PRODUTO VALUES (1, 1);
INSERT INTO TB_COMPRA_PRODUTO VALUES (1, 4);  
INSERT INTO TB_COMPRA_PRODUTO VALUES (2, 5);
INSERT INTO TB_COMPRA_PRODUTO VALUES (2, 6);
INSERT INTO TB_COMPRA_PRODUTO VALUES (3, 1);
INSERT INTO TB_COMPRA_PRODUTO VALUES (4, 2);
INSERT INTO TB_COMPRA_PRODUTO VALUES (6, 1);
INSERT INTO TB_COMPRA_PRODUTO VALUES (6, 5);
INSERT INTO TB_COMPRA_PRODUTO VALUES (7, 1);
INSERT INTO TB_COMPRA_PRODUTO VALUES (7, 6);
INSERT INTO TB_COMPRA_PRODUTO VALUES (8, 1);

-- TURNO --
INSERT INTO TB_TURNO VALUES ('MATINE')
INSERT INTO TB_TURNO VALUES ('NOITE')


-- SESSAO_TURNO --
INSERT INTO TB_SESSAO_TURNO VALUES (1,1)
INSERT INTO TB_SESSAO_TURNO VALUES (2,2)
INSERT INTO TB_SESSAO_TURNO VALUES (1,3)
INSERT INTO TB_SESSAO_TURNO VALUES (2,4)
INSERT INTO TB_SESSAO_TURNO VALUES (1,5)

select * from TB_SESSAO_TURNO