 -- 1. Qual o total de produtos vendidos em determinado período
 -- 2. Qual o valor total de produtos do snack bar vendidos por dias, meses e anos
CREATE TABLE AGREG_FATO_VENDA_PRODUTO_MENSAL (
	ID_AGREGADO INT IDENTITY(1,1),
	ID_TEMPO INT NOT NULL REFERENCES DIM_TEMPO(ID_TEMPO),
	ID_PLATAFORMA INT NOT NULL REFERENCES DIM_PLATAFORMA (ID_PLATAFORMA),
	ID_PRODUTO INT NOT NULL REFERENCES DIM_PRODUTO (ID_PRODUTO),
	VALOR_PAGO_TOTAL NUMERIC(10,2) NOT NULL,
	QUANTIDADE INT NOT NULL
)

-- 3. Quais filmes que mais venderam ingressos em julho
-- 4. Qual total de ingressos vendidos no ano de 2019
CREATE TABLE AGREG_FATO_VENDA_INGRESSO_MENSAL_ANUAL (
	ID INT IDENTITY(1,1),
	ID_TEMPO INT NOT NULL REFERENCES DIM_TEMPO(ID_TEMPO),
	ID_FILME INT NOT NULL REFERENCES DIM_FILME(ID_FILME),
	ID_INGRESSO INT NOT NULL REFERENCES DIM_INGRESSO (ID_INGRESSO),
	VALOR_PAGO_TOTAL NUMERIC(10,2) NOT NULL,
	QUANTIDADE INT NOT NULL
)
