USE CINEMA
GO 

CREATE TABLE  TB_AUX_FATO_VENDA_INGRESSO(
  DATA_CARGA DATETIME NOT NULL,
  COD_COMPRA VARCHAR(45) NOT NULL,
  DT_VENDA DATE NOT NULL,
  HORA_VENDA TIME NOT NULL,
  ID_INGRESSO INT NOT NULL,
  ID_ENDERECO INT NOT NULL,
  ID_PAGAMENTO INT NOT NULL,
  ID_CLIENTE INT NOT NULL ,
  ID_CINEMA INT NOT NULL,
  ID_PLATAFORMA INT NOT NULL,
  ID_FILME INT NOT NULL,
  ID_SESSAO INT NOT NULL,
  ID_PLANO INT NOT NULL,
  QUANTIDADE INT NULL,
  VALOR_PAGO NUMERIC(10,2) NULL
)


CREATE TABLE TB_AUX_FILME(
	DATA_CARGA DATETIME NOT NULL,
	COD_FILME INT NOT NULL,
	NM_FILME VARCHAR(45)  NULL,
	GR_FILME VARCHAR(45) NULL,
	PDT_FILME VARCHAR(45)  NULL,
	DIR_FILME VARCHAR(45)  NULL,
	DUR_FILME INT NULL
)

CREATE TABLE  TB_AUX_SESSAO(
	DATA_CARGA DATETIME NOT NULL,
	COD_SESSAO INT NOT NULL,
	HORA_SESSAO TIME  NULL,
	DATA_SESSAO DATE  NULL,
	LINGUAGEM_SESSAO VARCHAR(45) NULL,
)

CREATE TABLE TB_AUX_PLANO(
	DATA_CARGA DATETIME NOT NULL,
	COD_PLANO INT NOT NULL,
	TIPO_PLANO VARCHAR(45) NOT NULL
)

CREATE TABLE TB_AUX_INGRESSO(
	DATA_CARGA DATETIME NOT NULL,
	COD_INGRESSO INT NOT NULL,
	DISPONIBILIDADE VARCHAR(45),
	VALOR_INGRESSO NUMERIC(10,2)
)