CREATE TABLE TB_VIOLACAO_FATO_VENDA_INGRESSO(
  ID_FATO_INGRESSO INT IDENTITY(1,1) NOT NULL,
  DATA_CARGA DATETIME NOT NULL,
  COD_COMPRA VARCHAR(45) NOT NULL,
  DT_VENDA DATE NULL,
  HORA_VENDA TIME NULL,
  ID_INGRESSO INT NULL,
  ID_ENDERECO INT NULL,
  ID_PAGAMENTO INT NULL, 
  ID_CLIENTE INT NULL,
  ID_CINEMA INT NULL, 
  ID_PLATAFORMA INT NULL,
  ID_FILME INT NULL, 
  ID_SESSAO INT NULL,
  ID_PLANO INT NULL ,
  QUANTIDADE INT NULL,
  VALOR_PAGO NUMERIC(10,2) NULL,
  DATA_VIOLACAO DATETIME NOT NULL, 
  VIOLACAO VARCHAR(100) NOT NULL,
  PRIMARY KEY ( ID_FATO_INGRESSO)
)

CREATE TABLE TB_VIOLACAO_FILME(
  ID_FILME INT IDENTITY(1,1) NOT NULL,
  DATA_CARGA DATETIME NOT NULL,
  COD_FILME INT NOT NULL,
  NM_FILME VARCHAR(45) NULL,
  GR_FILME VARCHAR(45) NULL,
  PDT_FILME VARCHAR(45) NULL,
  DIR_FILME VARCHAR(45) NULL,
  DUR_FILME TIME NULL,
  DATA_VIOLACAO DATETIME NOT NULL, 
  VIOLACAO VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID_FILME)
)

CREATE TABLE  TB_VIOLACAO_SESSAO(
  ID_SESSAO INT IDENTITY(1,1) NOT NULL,
  DATA_CARGA DATETIME NOT NULL,
  COD_SESSAO INT NOT NULL,
  HORA_SESSAO TIME NULL,
  DATA_SESSAO DATE NULL,
  LINGUAGEM_SESSAO VARCHAR(25) NULL,
  DATA_VIOLACAO DATETIME NOT NULL, 
  VIOLACAO VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID_SESSAO)
)

CREATE TABLE TB_VIOLACAO_PLANO(
  ID_PLANO INT IDENTITY(1,1) NOT NULL,
  DATA_CARGA DATETIME NOT NULL,
  COD_PLANO INT NOT NULL,
  TIPO_PLANO VARCHAR(45) NULL,
  DATA_VIOLACAO DATETIME NOT NULL, 
  VIOLACAO VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID_PLANO)
)

CREATE TABLE TB_VIOLACAO_INGRESSO(
	ID_INGRESSO  INT IDENTITY(1,1) NOT NULL,
	DATA_CARGA DATETIME NOT NULL,
	COD_INGRESSO INT  NOT NULL,
	DISPONIBILIDADE VARCHAR(45) NULL,
	VALOR_INGRESSO NUMERIC(10,2) NULL,
	DATA_VIOLACAO DATETIME NOT NULL, 
  	VIOLACAO VARCHAR(100) NOT NULL,
  	PRIMARY KEY (ID_INGRESSO)
)
