/* CARGA PARA O TB_AUX_CLIENTE*/
CREATE PROCEDURE SP_OLTP_CLIENTE(@data DATETIME)
AS
BEGIN
	DECLARE @id INT, @codigo INT, @nome VARCHAR(45),@sobrenome VARCHAR(45),@DT_NASCIMENTO DATE
	DELETE FROM TB_AUX_CLIENTE WHERE DATA_CARGA = @data 

	DECLARE C_CLIENTE CURSOR FOR SELECT ID_CLIENTE,COD_CLIENTE FROM TB_CLIENTE 

END

SELECT * FROM TB_CLIENTE
SELECT * FROM TB_PESSOA