/* CARGA PARA O TB_AUX_CLIENTE*/
ALTER PROCEDURE SP_OLTP_CLIENTE(@data DATETIME)
AS
BEGIN
	DECLARE @id INT, @codigo INT,@cpf VARCHAR(15),@sexo varchar(1), @nome VARCHAR(45),@sobrenome VARCHAR(45),@dt_nascimento DATE
	DELETE FROM TB_AUX_CLIENTE WHERE DATA_CARGA = @data 

	DECLARE C_CLIENTE CURSOR FOR SELECT C.ID_CLIENTE,C.ID_PESSOA, P.CPF,P.SEXO,P.NOME, P.SOBRENOME,
										P.DATA_NASCIMENTO FROM TB_CLIENTE AS C
										INNER JOIN TB_PESSOA AS P ON (C.ID_PESSOA = P.ID_PESSOA)

	OPEN C_CLIENTE
	FETCH C_CLIENTE INTO @id, @codigo, @cpf,@sexo,@nome,@sobrenome,@dt_nascimento
	WHILE(@@FETCH_STATUS = 0)
		BEGIN 
			INSERT INTO TB_AUX_CLIENTE
			VALUES(@data, @id, @codigo, @cpf, @sexo, @nome, @sobrenome, @dt_nascimento)

			FETCH C_CLIENTE INTO @id, @codigo, @cpf,@sexo,@nome,@sobrenome,@dt_nascimento
		END
	CLOSE C_CLIENTE
	DEALLOCATE C_CLIENTE
END

EXEC SP_OLTP_CLIENTE '20190101'

SELECT * FROM TB_CLIENTE
SELECT * FROM TB_PESSOA
SELECT * FROM TB_AUX_CLIENTE

TRUNCATE TABLE TB_AUX_CLIENTE