/* CARGA PARA O TB_AUX_CLIENTE*/
CREATE PROCEDURE SP_OLTP_CLIENTE(@data DATETIME)
AS
BEGIN
	DECLARE @id INT, @codigo INT,@cpf VARCHAR(15),@sexo varchar(1), @nome VARCHAR(45),@sobrenome VARCHAR(45),@dt_nascimento DATE
	DELETE FROM TB_AUX_CLIENTE WHERE DATA_CARGA = @data 

	DECLARE C_CLIENTE CURSOR FOR SELECT C.ID_CLIENTE,C.ID_PESSOA, P.CPF,P.SEXO,P.NOME, P.SOBRENOME,
										P.DATA_NASCIMENTO FROM TB_CLIENTE AS C
										INNER JOIN TB_PESSOA AS P ON (C.ID_PESSOA = P.ID_PESSOA)

	OPEN C_CLIENTE
	FETCH C_CLIENTE INTO @id, @codigo, @cpf,@sexo,@nome,@sobrenome,@dt_nascimento
	WHILE(@@FETCH_STATUS = 0)
		BEGIN 
			INSERT INTO TB_AUX_CLIENTE
			VALUES(@data, @id, @codigo, @cpf, @sexo, @nome, @sobrenome, @dt_nascimento)

			FETCH C_CLIENTE INTO @id, @codigo, @cpf,@sexo,@nome,@sobrenome,@dt_nascimento
		END
	CLOSE C_CLIENTE
	DEALLOCATE C_CLIENTE
END

SELECT * FROM TB_AUX_ENDERECO_CLIENTE
SELECT * FROM TB_ENDERECO

CREATE PROCEDURE SP_OLTP_ENDERECO_CLIENTE(@data DATETIME)
AS
BEGIN

	DECLARE @id INT, @codigo VARCHAR(45), @rua VARCHAR(45), @numero VARCHAR(45), @cidade VARCHAR(45), @bairro VARCHAR(45), @estado VARCHAR(45), @cep VARCHAR(15)
	DELETE FROM TB_AUX_ENDERECO_CLIENTE WHERE DATA_CARGA = @data

	DECLARE C_ENDERECO CURSOR FOR SELECT ID_ENDERECO, RUA, NUMERO, CIDADE, BAIRRO, ESTADO, CEP  FROM TB_ENDERECO
END

