
CREATE DATABASE DW_CINEMA

DROP TABLE FATO_PRODUTO

SELECT * FROM FATO_PRODUTO
SELECT * FROM DIM_ENDERECO_CLIENTE
SELECT * FROM DIM_TEMPO
SELECT * FROM DIM_TIPO_PRODUTO
SELECT * FROM DIM_PAGAMENTO
SELECT * FROM DIM_CLIENTE
SELECT * FROM DIM_CINEMA

CREATE TABLE  FATO_PRODUTO(
  id_prod INT NOT NULL PRIMARY KEY,
  cod_prod INT NOT NULL,
  nm_prod VARCHAR(45) NULL,
  qtd_prod VARCHAR(45) NULL,
  valor_prod DECIMAL(10,2) NULL,
  id_end INT NOT NULL REFERENCES DIM_ENDERECO_CLIENTE(id_end),
  id_tem INT NOT NULL REFERENCES DIM_TEMPO(id_tem),
  id_tip INT NOT NULL REFERENCES DIM_TIPO_PRODUTO(id_tip),
  id_pag INT NOT NULL REFERENCES DIM_PAGAMENTO(id_pag),
  id_cli INT NOT NULL REFERENCES DIM_CLIENTE (id_cli),
  id_cin INT NOT NULL REFERENCES DIM_CINEMA (id_cin)
)

CREATE TABLE DIM_TEMPO (
  id_tem INT NOT NULL PRIMARY KEY,
  cod_tem VARCHAR(45) NOT NULL,
  Dia INT NOT NULL,
  Mes INT NOT NULL,
  Ano INT NOT NULL,
  NomeMes VARCHAR(20) NOT NULL,
  Trimestre INT NOT NULL,
  Turno VARCHAR(15) NOT NULL,
  Data DATETIME NOT NULL,
  Nivel VARCHAR(8) NOT NULL,
  DiaSemana VARCHAR(25) NOT NULL,
  Feriado CHAR(3) NOT NULL,
  Diautil CHAR(3) NOT NULL,
  FimSemana VARCHAR(45) NOT NULL,
  Quinzeza INT NOT NULL,
  FimMes CHAR(3) NOT NULL,
  NomeTrimestre VARCHAR(20) NOT NULL,
  Semestre INT NOT NULL,
  NomeSemestre VARCHAR(20) NOT NULL,
)

CREATE TABLE  DIM_CLIENTE(
  id_cli INT NOT NULL PRIMARY KEY,
  cod_cli INT NOT NULL,
  nm_cli VARCHAR(45) NULL,
  sbr_cli VARCHAR(45) NULL,
  dt_cli DATE NULL
)

CREATE TABLE DIM_ENDERECO_CLIENTE (
  id_end INT NOT NULL PRIMARY KEY,
  cod_end VARCHAR(45) NOT NULL,
  rua VARCHAR(45) NULL,
  numero VARCHAR(45) NULL,
  cidade VARCHAR(45) NULL,
  bairro VARCHAR(45) NULL,
  estado VARCHAR(45) NULL,
  cep VARCHAR(15) NULL
)

CREATE TABLE DIM_PLATAFORMA (
  id_pla INT NOT NULL PRIMARY KEY,
  cod_pla INT NOT NULL,
  tipo_pla VARCHAR(45) NULL
 )

CREATE TABLE DIM_TIPO_PRODUTO (
  id_tip INT NOT NULL PRIMARY KEY,
  cod_tip VARCHAR(45) NOT NULL,
  tipo_tip VARCHAR(45) NULL
)

CREATE TABLE  DIM_PAGAMENTO (
  id_pag INT NOT NULL PRIMARY KEY,
  cod_pag INT NOT NULL,
  tipo_pag VARCHAR(45) NULL,
)

CREATE TABLE DIM_CINEMA (
  id_cin INT NOT NULL PRIMARY KEY,
  nome_cin VARCHAR(45) NOT NULL,
  desc_cin VARCHAR NULL,
)
