
CREATE DATABASE DW_CINEMA

DROP TABLE FATO_PRODUTO

SELECT * FROM FATO_PRODUTO
SELECT * FROM DIM_ENDERECO_CLIENTE
SELECT * FROM DIM_TEMPO
SELECT * FROM DIM_TIPO_PRODUTO
SELECT * FROM DIM_PAGAMENTO
SELECT * FROM DIM_CLIENTE
SELECT * FROM DIM_CINEMA

DROP TABLE FATO_PRODUTO

CREATE TABLE  FATO_PRODUTO(
  id_fato_produto INT NOT NULL PRIMARY KEY,
  cod_produto INT NOT NULL,
  id_endereco INT NOT NULL REFERENCES DIM_ENDERECO_CLIENTE(id_endereco),
  id_tempo INT NOT NULL REFERENCES DIM_TEMPO(id_tempo),
  id_produto INT NOT NULL REFERENCES DIM_PRODUTO(id_produto),
  id_pagamento INT NOT NULL REFERENCES DIM_PAGAMENTO(id_pagamento),
  id_cliente INT NOT NULL REFERENCES DIM_CLIENTE (id_cliente),
  id_cinema INT NOT NULL REFERENCES DIM_CINEMA (id_cinema),
  id_plataforma INT NOT NULL REFERENCES DIM_PLATAFORMA (id_plataforma),
  quantidade INT
)

CREATE TABLE DIM_TEMPO (
  id_tempo INT NOT NULL PRIMARY KEY,
  cod_tempo VARCHAR(45) NOT NULL,
  Dia INT NOT NULL,
  Mes INT NOT NULL,
  Ano INT NOT NULL,
  NomeMes VARCHAR(20) NOT NULL,
  Trimestre INT NOT NULL,
  Turno VARCHAR(15) NOT NULL,
  Data DATETIME NOT NULL,
  Nivel VARCHAR(8) NOT NULL,
  DiaSemana VARCHAR(25) NOT NULL,
  Feriado CHAR(3) NOT NULL,
  Diautil CHAR(3) NOT NULL,
  FimSemana VARCHAR(45) NOT NULL,
  Quinzeza INT NOT NULL,
  FimMes CHAR(3) NOT NULL,
  NomeTrimestre VARCHAR(20) NOT NULL,
  Semestre INT NOT NULL,
  NomeSemestre VARCHAR(20) NOT NULL,
)

CREATE TABLE  DIM_CLIENTE(
  id_cliente INT NOT NULL PRIMARY KEY,
  cod_cliente INT NOT NULL,
  nm_cliente VARCHAR(45) NULL,
  sbr_cliente VARCHAR(45) NULL,
  dt_cliente DATE NULL
)

CREATE TABLE DIM_ENDERECO_CLIENTE (
  id_endereco INT NOT NULL PRIMARY KEY,
  cod_endereco VARCHAR(45) NOT NULL,
  rua VARCHAR(45) NULL,
  numero VARCHAR(45) NULL,
  cidade VARCHAR(45) NULL,
  bairro VARCHAR(45) NULL,
  estado VARCHAR(45) NULL,
  cep VARCHAR(15) NULL
)

CREATE TABLE DIM_PLATAFORMA (
  id_plataforma INT NOT NULL PRIMARY KEY,
  cod_plataforma INT NOT NULL,
  tipo_plataforma VARCHAR(45) NULL
 )

CREATE TABLE DIM_PRODUTO(
  id_produto INT NOT NULL PRIMARY KEY,
  cod_produto VARCHAR(45) NOT NULL,
  nm_produto VARCHAR(45) NULL,
  qtd_produto VARCHAR(45) NULL,
  valor_produto DECIMAL(10,2) NULL
)

CREATE TABLE  DIM_PAGAMENTO (
  id_pagamento INT NOT NULL PRIMARY KEY,
  cod_pagamento INT NOT NULL,
  tipo_pagamento VARCHAR(45) NULL,
)

CREATE TABLE DIM_CINEMA (
  id_cinema INT NOT NULL PRIMARY KEY,
  nome_cinema VARCHAR(45) NOT NULL,
  desc_cinema VARCHAR(100) NULL,
)
