 -- Qual o total de produtos vendidos em determinado período
 -- Qual o valor total de produtos do snack bar vendidos por dias, meses e anos
CREATE TABLE AGREG_FATO_VENDA_PRODUTO_MENSAL (
	ID INT IDENTITY(1,1),
	ID_TEMPO INT NOT NULL REFERENCES DIM_TEMPO(ID_TEMPO),
	ID_PLATAFORMA INT NOT NULL REFERENCES DIM_PLATAFORMA (ID_PLATAFORMA),
	VALOR_PAGO_TOTAL NUMERIC(10,2) NOT NULL,
	QUANTIDADE INT NOT NULL
)

-- Quais filmes que mais venderam ingressos por mês e ano
-- Qual total de ingressos vendidos em determinado período
CREATE TABLE AGREG_FATO_VENDA_INGRESSO_MENSAL_ANUAL (
	ID INT IDENTITY(1,1),
	ID_TEMPO INT NOT NULL REFERENCES DIM_TEMPO(ID_TEMPO),
	ID_FILME INT NOT NULL REFERENCES DIM_FILME(ID_FILME),
	VALOR_PAGO_TOTAL NUMERIC(10,2) NOT NULL,
	QUANTIDADE INT NOT NULL
)