CREATE TABLE TB_AUX_FATO_VENDA_PRODUTO(
	DATA_CARGA DATETIME NOT NULL,
	COD_PRODUTO INT NOT NULL,
	ID_ENDERECO INT NOT NULL, 
	ID_TEMPO INT NOT NULL, 
	ID_PRODUTO INT NOT NULL,
	ID_PAGAMENTO INT NOT NULL, 
	ID_CLIENTE INT NOT NULL, 
	ID_CINEMA INT NOT NULL, 
	ID_PLATAFORMA INT NOT NULL, 
	QUANTIDADE INT  NULL,
	VALOR_PAGO NUMERIC(10,2) NULL
)

CREATE TABLE  TB_AUX_CLIENTE(
	DATA_CARGA DATETIME NOT NULL,
	COD_CLIENTE INT NOT NULL,
	CPF VARCHAR(15) NULL,
	SEXO VARCHAR(1) NULL,
	NOME VARCHAR(45) NULL,
	SOBRENOME VARCHAR(45) NULL,
	DT_NASCIMENTO DATE NULL
)

CREATE TABLE TB_AUX_ENDERECO_CLIENTE (	
	DATA_CARGA DATETIME NOT NULL,
	COD_ENDERECO INT NOT NULL,
	RUA VARCHAR(45) NULL,
	NUMERO VARCHAR(45) NULL,
	CIDADE VARCHAR(45) NULL,
	BAIRRO VARCHAR(45) NULL,
	COMPLEMETO VARCHAR(45) NULL,
	ESTADO VARCHAR(45) NULL,
	CEP VARCHAR(15) NULL
)

CREATE TABLE TB_AUX_PLATAFORMA (
	DATA_CARGA  DATETIME NOT NULL,
	COD_PLATAFORMA INT NOT NULL,
	TIPO_PLATAFORMA VARCHAR(45) NULL
 )

 CREATE TABLE TB_AUX_PRODUTO(
	DATA_CARGA  DATETIME NOT NULL,
	COD_PRODUTO INT NOT NULL,
	NM_PRODUTO VARCHAR(45) NULL,
	VALOR_PRODUTO NUMERIC(10,2) NULL
)

CREATE TABLE  TB_AUX_PAGAMENTO (
	DATA_CARGA DATETIME NOT NULL,
    COD_PAGAMENTO INT NOT NULL,
    TIPO_PAGAMENTO VARCHAR(25) NULL,
    VALOR_PAGAMENTO NUMERIC(10,2) NULL
)	

CREATE TABLE TB_AUX_CINEMA (
	DATA_CARGA DATETIME NOT NULL,
	COD_CINEMA INT NOT NULL,
	NOME_CINEMA VARCHAR(45) NULL,
	DESC_CINEMA VARCHAR(100) NULL
)
