CREATE TABLE  TB_AUX_FATO_VENDA_INGRESSO(
  DATA_CARGA DATETIME NOT NULL,
  COD_INGRESSO VARCHAR(45) NOT NULL,
  ID_INGRESSO INT NOT NULL,
  ID_ENDERECO INT NOT NULL,
  ID_TEMPO INT NOT NULL,
  ID_PAGAMENTO INT NOT NULL,
  ID_CLIENTE INT NOT NULL ,
  ID_CINEMA INT NOT NULL,
  ID_PLATAFORMA INT NOT NULL,
  ID_TURNO INT NOT NULL,
  ID_FILME INT NOT NULL,
  ID_SESSAO INT NOT NULL,
  ID_PLANO INT NOT NULL,
  ID_PRECO INT NOT NULL,
  QUATIDADE INT NOT NULL,
  VALOR_PAGO NUMERIC(10,2)
)


CREATE TABLE TB_AUX_FILME(
	DATA_CARGA DATETIME NOT NULL,
	COD_FILME INT NOT NULL,
	NM_FILME VARCHAR(45) NOT NULL,
	GR_FILME VARCHAR(45) NOT NULL,
	PDT_FILME VARCHAR(45) NOT NULL,
	DIR_FILME VARCHAR(45) NOT NULL,
	DUR_FILME TIME NOT NULL
)

CREATE TABLE  TB_AUX_PLANO(
	DATA_CARGA DATETIME NOT NULL,
	COD_PLANO VARCHAR(45) NOT NULL,
	VIVO_VALORIZA VARCHAR(45) NULL DEFAULT NULL,
	VALE_CULTURA VARCHAR(45) NULL DEFAULT NULL
)

CREATE TABLE  TB_AUX_PRECO(
	DATA_CARGA DATETIME NOT NULL,
	COD_PRECO VARCHAR(45) NOT NULL,
	VALOR_PRECO NUMERIC(10,2)
)

CREATE TABLE  TB_AUX_SESSAO(
	DATA_CARGA DATETIME NOT NULL,
	COD_SESSAO INT NOT NULL,
	HORA_SESSAO TIME NOT NULL,
	DATA_SESSAO DATE NOT NULL,
	LINGUAGEM_SESSAO VARCHAR(25) NOT NULL,
)
CREATE TABLE TB_AUX_INGRESSO (
	DATA_CARGA DATETIME NOT NULL,
	COD_INGRESSO INT NOT NULL,
	DISPONIBILIDADE VARCHAR(45) NOT NULL,
	VALOR_INGRESSO NUMERIC (10,2) NOT NULL
)
