CREATE TABLE TB_VIOLACAO_CLIENTE (
	ID INT IDENTITY (1,1) NOT NULL, --
	DATA_CARGA DATETIME NOT NULL,
	COD_ENDERECO INT NOT NULL,
	RUA VARCHAR(45) NULL,
	NUMERO VARCHAR(45) NULL,
	CIDADE VARCHAR(45) NULL,
	BAIRRO VARCHAR(45) NULL,
	COMPLEMETO VARCHAR(45) NULL,
	ESTADO VARCHAR(45) NULL,
	CEP VARCHAR(15) NULL,
	DIA DATETIME NULL,
	DATA_VIOLACAO DATETIME NOT NULL, -- 
	VIOLACAO VARCHAR(100) NOT NULL, --
	PRIMARY KEY (ID)
)

CREATE TABLE TB_VIOLACAO_ENDERECO_CLIENTE (
	ID INT IDENTITY (1,1) NOT NULL, --
	DATA_CARGA DATETIME NOT NULL,
	COD_ENDERECO INT NOT NULL,
	RUA VARCHAR(45) NULL,
	NUMERO VARCHAR(45) NULL,
	CIDADE VARCHAR(45) NULL,
	BAIRRO VARCHAR(45) NULL,
	COMPLEMETO VARCHAR(45) NULL,
	ESTADO VARCHAR(45) NULL,
	CEP VARCHAR(15) NULL,
	DATA_VIOLACAO DATETIME NOT NULL, -- 
	VIOLACAO VARCHAR(100) NOT NULL, --
	PRIMARY KEY (ID)
)

CREATE TABLE TB_VIOLACAO_FATO_VENDA_PRODUTO(
	ID INT IDENTITY (1,1) NOT NULL, --
	DATA_CARGA DATETIME NOT NULL,
	COD_COMPRA INT NOT NULL,
	DT_VENDA DATE NOT NULL,
	HORA_VENDA TIME NOT NULL,
	ID_ENDERECO INT NOT NULL, 
	ID_PRODUTO INT NOT NULL,
	TIPO_PAGAMENTO VARCHAR(25) NOT NULL, 
	ID_CLIENTE INT NOT NULL, 
	ID_CINEMA INT NOT NULL, 
	ID_PLATAFORMA INT NOT NULL, 
	VALOR_PAGO NUMERIC(10,2) NULL,
	QUANTIDADE INT  NULL,
	DATA_VIOLACAO DATETIME NOT NULL, --
	VIOLACAO VARCHAR(100) NOT NULL, --
	PRIMARY KEY (ID)
	
)

CREATE TABLE TB_VIOLACAO_PLATAFORMA (
	ID INT IDENTITY (1,1) NOT NULL, --
	DATA_CARGA  DATETIME NOT NULL,
	COD_PLATAFORMA INT NOT NULL,
	TIPO_PLATAFORMA VARCHAR(45) NULL,
	DATA_VIOLACAO DATETIME NOT NULL, --
	VIOLACAO VARCHAR(100) NOT NULL, --
	PRIMARY KEY (ID)
 )
 
 CREATE TABLE TB_VIOLACAO_PRODUTO(
	ID INT IDENTITY (1,1) NOT NULL, --
	DATA_CARGA  DATETIME NOT NULL,
	COD_PRODUTO INT NOT NULL,
	NM_PRODUTO VARCHAR(45) NULL,
	VALOR_PRODUTO NUMERIC(10,2) NULL,
	DATA_VIOLACAO DATETIME NOT NULL, --
	VIOLACAO VARCHAR(100) NOT NULL, --
	PRIMARY KEY (ID)
)

CREATE TABLE  TB_VIOLACAO_PAGAMENTO (
	ID INT IDENTITY (1,1) NOT NULL, --
	DATA_CARGA DATETIME NOT NULL,
    COD_PAGAMENTO INT NOT NULL,
    TIPO_PAGAMENTO VARCHAR(25) NULL,
    VALOR_PAGAMENTO NUMERIC(10,2) NULL,
	DATA_VIOLACAO DATETIME NOT NULL, --
	VIOLACAO VARCHAR(100) NOT NULL, --
	PRIMARY KEY (ID)
)

CREATE TABLE TB_VIOLACAO_CINEMA (
	ID INT IDENTITY (1,1) NOT NULL, --
	DATA_CARGA DATETIME NOT NULL,
	COD_CINEMA INT NOT NULL,
	NOME_CINEMA VARCHAR(45) NULL,
	DESC_CINEMA VARCHAR(100) NULL,
	DATA_VIOLACAO DATETIME NOT NULL, --
	VIOLACAO VARCHAR(100) NOT NULL, --
	PRIMARY KEY (ID)
)
CREATE TABLE TB_VIOLACAO_TURNO(
	ID INT IDENTITY (1,1) NOT NULL, --
	DATA_CARGA DATETIME NOT NULL,
	COD_TURNO INT NOT NULL,
	TIPO VARCHAR(20),
	DATA_VIOLACAO DATETIME NOT NULL, --
	VIOLACAO VARCHAR(100) NOT NULL, --
	PRIMARY KEY (ID)
)

