CREATE TABLE  FATO_VENDA_INGRESSO(
  ID_FATO_INGRESSO INT NOT NULL,
  DATA_CARGA DATETIME NOT NULL,
  COD_COMPRA VARCHAR(45) NULL,
  ID_INGRESSO INT NULL,
  ID_ENDERECO INT NULL,
  ID_TEMPO INT NULL, 
  ID_PAGAMENTO INT NULL, 
  ID_CLIENTE INT NULL,
  ID_CINEMA INT NULL, 
  ID_PLATAFORMA INT NULL,
  ID_TURNO INT NULL, 
  ID_FILME INT NULL, 
  ID_SESSAO INT NULL,
  ID_PLANO INT NULL ,
  QUATIDADE INT NULL,
  VALOR_PAGO NUMERIC(10,2) NULL,
  DATA_VIOLACAO DATETIME NOT NULL, 
  VIOLACAO VARCHAR(100) NOT NULL,
  PRIMARY KEY ( ID_FATO_INGRESSO)
)

CREATE TABLE DIM_FILME(
  ID_FILME INT NOT NULL,
  DATA_CARGA DATETIME NOT NULL,
  COD_FILME INT NULL,
  NM_FILME VARCHAR(45) NULL,
  GR_FILME VARCHAR(45) NULL,
  PDT_FILME VARCHAR(45) NULL,
  DIR_FILME VARCHAR(45) NULL,
  DUR_FILME TIME NULL,
  DATA_VIOLACAO DATETIME NOT NULL, 
  VIOLACAO VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID_FILME)
)

CREATE TABLE  DIM_SESSAO(
  ID_SESSAO INT NOT NULL,
  DATA_CARGA DATETIME NOT NULL,
  HORA_SESSAO TIME NULL,
  DATA_SESSAO DATE NULL,
  LINGUAGEM_SESSAO VARCHAR(25) NULL,
  DATA_VIOLACAO DATETIME NOT NULL, 
  VIOLACAO VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID_SESSAO)
)

CREATE TABLE DIM_PLANO(
  ID_PLANO INT NOT NULL,
  DATA_CARGA DATETIME NOT NULL,
  TIPO_PLANO VARCHAR(45) NULL,
  DATA_VIOLACAO DATETIME NOT NULL, 
  VIOLACAO VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID_PLANO)
)