USE CINEMA
GO 


---------------------------------PROCEDIMENTOS DE CARGA DOS AGREGADOS--------------------------------

CREATE PROCEDURE SP_AGREG_FATO_VENDA_PRODUTO_MENSAL
AS
BEGIN
	DECLARE @id_tempo INT, @id_plataforma INT, @id_produto INT, @quantidade INT, @valor_pago NUMERIC(10,2)
	DELETE FROM AGREG_FATO_VENDA_PRODUTO_MENSAL
	DECLARE C_AGREG_MENSAL CURSOR FOR SELECT T.ID_TEMPO, P.ID_PRODUTO, O.ID_PLATAFORMA, SUM(F.QUANTIDADE), SUM(F.VALOR_PAGO) 
									  FROM FATO_VENDA_PRODUTO AS F
									  JOIN DIM_TEMPO AS T ON(F.ID_TEMPO = T.ID_TEMPO)
									  JOIN DIM_PRODUTO AS P ON(F.ID_PRODUTO = P.ID_PRODUTO)
									  JOIN DIM_PLATAFORMA AS O ON(F.ID_PLATAFORMA = O.ID_PLATAFORMA)
									  GROUP BY T.ID_TEMPO, P.ID_PRODUTO, O.ID_PLATAFORMA

	OPEN C_AGREG_MENSAL 
	
	FETCH C_AGREG_MENSAL INTO @id_tempo, @id_produto, @id_plataforma, @quantidade, @valor_pago
	WHILE(@@FETCH_STATUS = 0)
		BEGIN
			INSERT INTO AGREG_FATO_VENDA_PRODUTO_MENSAL(ID_TEMPO, ID_PLATAFORMA,ID_PRODUTO, VALOR_PAGO_TOTAL, QUANTIDADE)
			VALUES(@id_tempo,@id_plataforma,@id_produto, @valor_pago, @quantidade)

			FETCH C_AGREG_MENSAL INTO @id_tempo, @id_produto, @id_plataforma, @quantidade, @valor_pago
		END
	CLOSE C_AGREG_MENSAL
	DEALLOCATE C_AGREG_MENSAL
END 

GO

CREATE PROCEDURE SP_AGREG_FATO_VENDA_INGRESSO_MENSAL
AS
BEGIN
	DECLARE @id_tempo INT, @id_filme INT, @id_ingresso INT, @quantidade INT, @valor_pago NUMERIC(10,2) 

	DELETE FROM AGREG_FATO_VENDA_INGRESSO_MENSAL

	DECLARE C_AGREG_INGR CURSOR FOR SELECT T.ID_TEMPO, F.ID_FILME, I.ID_INGRESSO, SUM(FA.QUANTIDADE), SUM(FA.VALOR_PAGO)
									FROM FATO_VENDA_INGRESSO AS FA
									JOIN DIM_TEMPO AS T ON(FA.ID_TEMPO = T.ID_TEMPO)
									JOIN DIM_FILME AS F ON(FA.ID_FILME = F.ID_FILME)
									JOIN DIM_INGRESSO AS I ON(FA.ID_INGRESSO = I.ID_INGRESSO)
									GROUP BY T.ID_TEMPO, F.ID_FILME, I.ID_INGRESSO

	OPEN C_AGREG_INGR 
	FETCH C_AGREG_INGR INTO @id_tempo, @id_filme, @id_ingresso, @quantidade, @valor_pago
	
	WHILE(@@FETCH_STATUS = 0)
		BEGIN
			INSERT INTO AGREG_FATO_VENDA_INGRESSO_MENSAL( ID_TEMPO, ID_FILME, ID_INGRESSO, VALOR_PAGO_TOTAL, QUANTIDADE)
			VALUES(@id_tempo, @id_filme, @id_ingresso, @valor_pago, @quantidade)

			FETCH C_AGREG_INGR INTO @id_tempo, @id_filme, @id_ingresso, @quantidade, @valor_pago

		END
	CLOSE C_AGREG_INGR
	DEALLOCATE C_AGREG_INGR
END
