USE CINEMA 
GO

CREATE PROCEDURE POV_DIM_1 (@data_carga DATETIME)
AS
BEGIN
	EXEC SP_DIM_TEMPO '20150101','20190101'
	EXEC SP_DIM_CLIENTE @data_carga
	EXEC SP_DIM_CINEMA @data_carga
	EXEC SP_DIM_ENDERECO_CLIENTE @data_carga
	EXEC SP_DIM_FILME @data_carga
	EXEC SP_DIM_PAGAMENTO @data_carga
	EXEC SP_DIM_INGRESSO @data_carga
	EXEC SP_DIM_PLANO @data_carga
	EXEC SP_DIM_PLATAFORMA @data_carga
	EXEC SP_DIM_PRODUTO @data_carga
	EXEC SP_DIM_SESSAO @data_carga
	EXEC SP_DIM_TURNO @data_carga
	EXEC SP_FATO_VENDA_PRODUTO @data_carga
	EXEC SP_FATO_VENDA_INGRESSO @data_carga
END


GO

EXEC POV_DIM_1 '20180101'

