
USE CINEMA
GO

/* 1.Quantidade de ingressos vendidos por gênero de filme? */ -- OK
SELECT D.GR_FILME  AS 'GENERO FILME', SUM(d.ID_FILME) AS 'TOTAL DE INGRESSOS' 
FROM DIM_FILME D
INNER JOIN FATO_VENDA_INGRESSO V ON (V.ID_FILME = D.ID_FILME)
GROUP BY GR_FILME
HAVING SUM(D.ID_FILME) IS NOT NULL ORDER BY 'TOTAL DE INGRESSOS'




/* 2.Quais os dias, meses e anos que mais venderam ingressos? */ -- OK
SELECT SUM(A.QUANTIDADE) AS 'QUANTIDADE DE IGRESSOS', B.DIA_SEMANA AS DIA, B.NOME_MES AS MES, B.ANO 
FROM FATO_VENDA_INGRESSO A
INNER JOIN DIM_TEMPO B ON (A.ID_TEMPO = B.ID_TEMPO)
GROUP BY DIA_SEMANA, NOME_MES, ANO
HAVING SUM(A.QUANTIDADE) IS NOT NULL




/* 3.Qual o total de ingressos vendidos por filme e por período? */ 
SELECT F.NM_FILME AS FILME, T.DIA_SEMANA AS DIA, T.NOME_MES AS MES, T.ANO, SUM(I.QUANTIDADE) AS 'TOTAL DE INGRESSOS VENDIDOS' 
FROM FATO_VENDA_INGRESSO I
INNER JOIN DIM_TEMPO T ON (I.ID_TEMPO = T.ID_TEMPO)
INNER JOIN DIM_FILME f on (I.ID_FILME = F.ID_FILME)
GROUP BY F.NM_FILME, DIA_SEMANA , NOME_MES, ANO
HAVING SUM(I.QUANTIDADE) IS NOT NULL


/* 4.Quantidade de ingressos vendidos por plataformas por período? */ -- OK
SELECT SUM(A.QUANTIDADE) AS 'TOTAL INGRESSOS PRESENCIAL', B.DIA_SEMANA AS DIA, B.NOME_MES AS MES,
B.ANO, C.TIPO_PLATAFORMA AS 'TIPO PLATAFORMA'  FROM FATO_VENDA_INGRESSO A
INNER JOIN DIM_TEMPO B ON (A.ID_TEMPO = B.ID_TEMPO)
INNER JOIN DIM_PLATAFORMA C ON (A.ID_PLATAFORMA = C.ID_PLATAFORMA)
GROUP BY DIA_SEMANA,NOME_MES,ANO, C.TIPO_PLATAFORMA
HAVING SUM(A.QUANTIDADE) IS NOT NULL



/* 5.Quais os filmes que mais venderam ingressos no ano? */ --OK
SELECT TOP(3) A.NM_FILME AS FILMES, B.QUANTIDADE AS 'QUANTIDADE INGRESSOS VENDIDOS', P.TIPO_PLATAFORMA AS PLATAFORMA  
FROM DIM_FILME A
INNER JOIN FATO_VENDA_INGRESSO B ON (A.ID_FILME = B.ID_FILME)
INNER JOIN DIM_TEMPO C ON (B.ID_TEMPO = C.ID_TEMPO)
INNER JOIN DIM_PLATAFORMA P ON (P.ID_PLATAFORMA = B.ID_PLATAFORMA)
GROUP BY A.NM_FILME, P.TIPO_PLATAFORMA, B.QUANTIDADE



/* 6.Qual o valor total de ingressos vendidos por dias, meses e anos? */ -- OK
SELECT SUM(A.VALOR_PAGO) AS VALOR_PAGO_TOTAL, T.DIA, T.MES, T.ANO FROM FATO_VENDA_INGRESSO A
INNER JOIN DIM_TEMPO AS T ON (T.ID_TEMPO = A.ID_TEMPO )
GROUP BY DIA, MES, ANO
HAVING SUM(A.VALOR_PAGO) IS NOT NULL


/* 7.Qual o valor total de ingressos vendidos por plataformas em dias, meses e anos? */ -- OK

SELECT SUM(A.VALOR_PAGO) AS 'VALOR DO INGRESSOS',
B.DIA_SEMANA AS DIA, B.NOME_MES AS MES ,B.ANO, C.TIPO_PLATAFORMA AS PLATAFORMA 
FROM FATO_VENDA_INGRESSO A
INNER JOIN DIM_TEMPO B ON (A.ID_TEMPO = B.ID_TEMPO)
INNER JOIN DIM_PLATAFORMA C ON (A.ID_PLATAFORMA = C.ID_PLATAFORMA)
GROUP BY DIA_SEMANA, NOME_MES,ANO, C.TIPO_PLATAFORMA
HAVING SUM(A.QUANTIDADE) IS NOT NULL

/* 8.Qual a quantidade de clientes por determinado bairro, cidade e estado? */ -- OK
SELECT  E.BAIRRO, E.CIDADE, E.ESTADO,SUM(C.ID_CLIENTE) AS Quantidade FROM DIM_CLIENTE C
INNER JOIN FATO_VENDA_INGRESSO I ON (I.ID_CLIENTE = C.ID_CLIENTE)
INNER JOIN DIM_ENDERECO_CLIENTE E ON (I.ID_ENDERECO = E.ID_ENDERECO)
GROUP BY BAIRRO, CIDADE, ESTADO
HAVING SUM(C.ID_CLIENTE) IS NOT NULL

/* 9.Qual o turno que mais vendeu ingressos? */ -- OK
SELECT TOP 1 (T.TIPO), I.QUANTIDADE FROM FATO_VENDA_INGRESSO I
INNER JOIN DIM_TURNO T ON (I.ID_FATO_INGRESSO = T.ID_TURNO)
GROUP BY TIPO, I.QUANTIDADE

/* 10.Total de clientes por plano de desconto utilizado? */ -- OK
SELECT P.TIPO_PLANO, SUM(C.ID_CLIENTE) AS TOTAL_CLIENTE FROM FATO_VENDA_INGRESSO I
INNER JOIN DIM_CLIENTE C ON (I.ID_CLIENTE = C.ID_CLIENTE)
INNER JOIN DIM_PLANO P ON (I.ID_PLANO = P.ID_PLANO)
GROUP BY P.TIPO_PLANO
HAVING SUM(C.ID_CLIENTE) IS NOT NULL
