-- 1. Qual o total de produtos vendidos em determinado período?

SELECT sum(A.QUANTIDADE) AS TOTAL, B.MES, B.ANO, C.NM_PRODUTO AS NOME_DO_PRODUTO FROM AGREG_FATO_VENDA_PRODUTO_MENSAL A
INNER JOIN DIM_TEMPO B ON (A.ID_TEMPO = B.ID_TEMPO)
INNER JOIN DIM_PRODUTO C ON (A.ID_PRODUTO = C.ID_PRODUTO)
GROUP BY MES, ANO, NM_PRODUTO
HAVING SUM(A.QUANTIDADE) IS NOT NULL

-- 2. Qual o total de produtos vendidos por plataforma em determinado período?

SELECT P.TIPO_PLATAFORMA, B.NOME_MES, B.ANO, SUM(A.VALOR_PAGO_TOTAL) AS VALOR_PAGO_TOTAL FROM AGREG_FATO_VENDA_PRODUTO_MENSAL A
INNER JOIN DIM_TEMPO B ON (A.ID_TEMPO = B.ID_TEMPO)
INNER JOIN DIM_PLATAFORMA P ON (P.ID_PLATAFORMA = A.ID_PLATAFORMA)
WHERE TIPO_PLATAFORMA = 'PRESENCIAL'
GROUP BY NOME_MES, ANO, TIPO_PLATAFORMA
HAVING SUM(A.VALOR_PAGO_TOTAL) IS NOT NULL

SELECT P.TIPO_PLATAFORMA, B.NOME_MES, B.ANO, SUM(A.VALOR_PAGO_TOTAL) AS VALOR_PAGO_TOTAL FROM AGREG_FATO_VENDA_PRODUTO_MENSAL A
INNER JOIN DIM_TEMPO B ON (A.ID_TEMPO = B.ID_TEMPO)
INNER JOIN DIM_PLATAFORMA P ON (P.ID_PLATAFORMA = A.ID_PLATAFORMA)
WHERE TIPO_PLATAFORMA = 'ONLINE'
GROUP BY NOME_MES, ANO, TIPO_PLATAFORMA
HAVING SUM(A.VALOR_PAGO_TOTAL) IS NOT NULL
 
-- 4. Qual o total de ingressos vendidos em determinado período?

SELECT SUM(A.QUANTIDADE) AS TOTAL, B.NOME_MES, B.ANO FROM AGREG_FATO_VENDA_INGRESSO_MENSAL A
INNER JOIN DIM_TEMPO B ON (A.ID_TEMPO = B.ID_TEMPO)
INNER JOIN DIM_INGRESSO P ON (P.ID_INGRESSO = A.ID_INGRESSO)
GROUP BY NOME_MES, ANO
HAVING SUM(A.QUANTIDADE) IS NOT NULL
 